"""add extra movie columns

Revision ID: 1b23948339cd
Revises: bc549d6ce043
Create Date: 2025-11-05 14:17:22.841020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b23948339cd'
down_revision = 'bc549d6ce043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('time_watching', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chair_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hall_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('movie_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('quality',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('quality',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('movie_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('hall_name')
        batch_op.drop_column('chair_number')
        batch_op.drop_column('image')
        batch_op.drop_column('time_watching')
        batch_op.drop_column('role')
        batch_op.drop_column('director')
        batch_op.drop_column('year')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
