"""Add trailer columns

Revision ID: bc549d6ce043
Revises: eb8bffe26623
Create Date: 2025-11-04 10:22:05.559759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc549d6ce043'
down_revision = 'eb8bffe26623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trailer_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('trailer_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('trailer_file')
        batch_op.drop_column('trailer_url')

    # ### end Alembic commands ###
